version: "3.6"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: GeolocalizacionDb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  webapi.mongodb:
    container_name: javis86.geolocalizador.api
    ports:
      - 5002:80
    image: javis86.geolocalizador.api
    build:
      context: src/javis86.geolocalizador.api/.
    restart: on-failure
    depends_on:
      - mongodb